import { HomepageSection, FAQ } from "./types";

// ─── BY SEASON ─────────────────────────────────────────────
export const seasonSections: HomepageSection[] = [
  {
    id: "summer-dresses",
    title: "Summer Wedding Guest Dresses",
    description: "Light, breezy dresses perfect for outdoor summer weddings. Think flowy fabrics, bright colors, and flattering silhouettes that keep you cool and stylish.",
    slug: "summer-wedding-guest-dresses",
    products: [
      {
        title: "ZESICA Women's Summer Strapless Floral Midi Dress 2026 Bodycon Mesh Tube Wedd...",
        image: "https://m.media-amazon.com/images/I/71UczIhC4bL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FXWCV32B?tag=values0d4-20",
        price: "$58.99",
        rating: 4.6,
        reviewCount: 102,
      },
      {
        title: "ZESICA Women's Summer Short Sleeve Floral Bodycon Dress 2026 Ruched Mesh Wedd...",
        image: "https://m.media-amazon.com/images/I/71lDmsv+04L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0G3P62SJ7?tag=values0d4-20",
        price: "$48.99",
        rating: 4.5,
        reviewCount: 83,
      },
      {
        title: "Simplee Womens Floral Maxi Dress Short Sleeve Summer Boho Wedding Guest Dress...",
        image: "https://m.media-amazon.com/images/I/71jW7X+kpCL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DPJ8Q3CN?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 579,
      },
      {
        title: "PRETTYGARDEN Women's 2026 Spring Floral Spaghetti Strap Maxi Dress Stretch Se...",
        image: "https://m.media-amazon.com/images/I/61M7t3v6iUL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CNP4N39J?tag=values0d4-20",
        price: "$39.98",
        rating: 4.5,
        reviewCount: 1340,
      },
      {
        title: "PRETTYGARDEN Women's Summer Floral One Shoulder Maxi Dress Knot Ruffle Boho B...",
        image: "https://m.media-amazon.com/images/I/71ZTGUNM7aL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BVLLBDJ4?tag=values0d4-20",
        price: "$42.99",
        rating: 4.2,
        reviewCount: 7442,
      },
      {
        title: "ANRABESS Womens Summer Floral Dress V Neck Sleeveless A Line Wedding Guest Ma...",
        image: "https://m.media-amazon.com/images/I/710AZKcEgYL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0G1X25PWF?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 59,
      },
      {
        title: "PRETTYGARDEN Women's 2026 Summer Satin Dress Elegant Sleeveless Mock Neck Coc...",
        image: "https://m.media-amazon.com/images/I/71dn+reTqGL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C36765CP?tag=values0d4-20",
        price: "$59.99",
        rating: 4,
        reviewCount: 4726,
      },
      {
        title: "Women Sexy V Neck Sleeveless Mesh Ruffle Hem Bodycon Maxi Casual Backless Hig...",
        image: "https://m.media-amazon.com/images/I/51Rvv3xV60L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DCVPKW7H?tag=values0d4-20",
        price: "$40.49",
        rating: 4.2,
        reviewCount: 1107,
      },
    ],
  },
  {
    id: "fall-dresses",
    title: "Fall Wedding Guest Dresses",
    description: "Rich colors and elegant styles for autumn celebrations. From jewel tones to long sleeves, find dresses that complement the season beautifully.",
    slug: "fall-wedding-guest-dresses",
    products: [
      {
        title: "BTFBM Women's Maxi Dresses Spring 2026 Long Sleeve Ruched Bodycon Solid Ruffl...",
        image: "https://m.media-amazon.com/images/I/61O3xesrizL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FDKTCS7L?tag=values0d4-20",
        price: "$46.99",
        rating: 4.4,
        reviewCount: 559,
      },
      {
        title: "Verdusa Women's Floral Mesh Maxi Dresses Elegant Formal Long Sleeve Spring We...",
        image: "https://m.media-amazon.com/images/I/61NXa9j1ztL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F297J7G3?tag=values0d4-20",
        price: "$52.99",
        rating: 4.2,
        reviewCount: 330,
      },
      {
        title: "ZESICA Women's Long Sleeve Floral Bodycon Dress 2026 Spring Fall Ruched Mesh ...",
        image: "https://m.media-amazon.com/images/I/617sy+YX12L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH5BTXXW?tag=values0d4-20",
        price: "$52.99",
        rating: 4.5,
        reviewCount: 649,
      },
      {
        title: "REORIA Long Sleeve Wedding Guest Maxi Dresses for Women Sheer Mesh Square Nec...",
        image: "https://m.media-amazon.com/images/I/610QlJ04yoL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH6PH41V?tag=values0d4-20",
        price: "$49.97",
        rating: 4.5,
        reviewCount: 500,
      },
      {
        title: "REORIA Women's Fall Mesh Sheer Long Sleeve Midi Ruched Bodycon Dress Mock Nec...",
        image: "https://m.media-amazon.com/images/I/51vGGi9xm0L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FKTFJF68?tag=values0d4-20",
        price: "$49.97",
        rating: 4.6,
        reviewCount: 190,
      },
      {
        title: "GothDark Womens Floral Maxi Dress Sheer Mesh Bell Sleeve Tiered Ruffle Gothic...",
        image: "https://m.media-amazon.com/images/I/61pjj-1NYOL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FR4BKBQ6?tag=values0d4-20",
        price: "$37.99",
        rating: 4.5,
        reviewCount: 188,
      },
      {
        title: "BORIFLORS Women's Bodycon Ruched Mesh Long Sleeve Maxi Dress Mermaid Ruffle F...",
        image: "https://m.media-amazon.com/images/I/610oYJOTq5L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FX2MZQQW?tag=values0d4-20",
        price: "$35.99",
        rating: 4.4,
        reviewCount: 170,
      },
      {
        title: "GothDark Women's Summer Floral Mesh Ruffle Dress Short Sleeve Round Neck Wais...",
        image: "https://m.media-amazon.com/images/I/71HkhVu9R1L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DZT5LR5V?tag=values0d4-20",
        price: "$38.99",
        rating: 4.3,
        reviewCount: 243,
      },
    ],
  },
  {
    id: "spring-dresses",
    title: "Spring Wedding Guest Dresses",
    description: "Fresh and feminine dresses perfect for spring weddings. Pastels, florals, and elegant cuts that capture the spirit of the season.",
    slug: "spring-wedding-guest-dresses",
    products: [
      {
        title: "PRETTYGARDEN Maxi Dresses for Women 2026 Summer Tiered Floral Beach Sundress ...",
        image: "https://m.media-amazon.com/images/I/71wgrAHS4yL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DNLX4VH9?tag=values0d4-20",
        price: "$45.99",
        rating: 4.4,
        reviewCount: 711,
      },
      {
        title: "KUTUMAI Off The Shoulder Maxi Long Dress Corset Ruched Bodycon Cocktail Forma...",
        image: "https://m.media-amazon.com/images/I/61iTzc-omrL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F4MLXFHF?tag=values0d4-20",
        price: "$63.99",
        rating: 4.4,
        reviewCount: 1015,
      },
      {
        title: "Annebouti Women 2026 Summer Spring Ruched Maxi Dress Adjustable Spaghetti Str...",
        image: "https://m.media-amazon.com/images/I/81uDjUGXn7L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DR8J1J89?tag=values0d4-20",
        price: "$35.99",
        rating: 4.5,
        reviewCount: 903,
      },
      {
        title: "PRETTYGARDEN Women's 2026 Summer Satin Dress Elegant Sleeveless Mock Neck Coc...",
        image: "https://m.media-amazon.com/images/I/71dn+reTqGL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C36CZDD6?tag=values0d4-20",
        price: "$59.99",
        rating: 4,
        reviewCount: 4726,
      },
      {
        title: "ZESICA Women's Summer Strapless Floral Midi Dress 2026 Bodycon Mesh Tube Wedd...",
        image: "https://m.media-amazon.com/images/I/71UczIhC4bL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FXWCV32B?tag=values0d4-20",
        price: "$58.99",
        rating: 4.6,
        reviewCount: 102,
      },
      {
        title: "Women Sexy V Neck Sleeveless Mesh Ruffle Hem Bodycon Maxi Casual Backless Hig...",
        image: "https://m.media-amazon.com/images/I/51Rvv3xV60L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DCVPKW7H?tag=values0d4-20",
        price: "$40.49",
        rating: 4.2,
        reviewCount: 1107,
      },
      {
        title: "GRACE KARIN Summer Floral Dress for Women 2026,Off The Shoulder Smocked Bride...",
        image: "https://m.media-amazon.com/images/I/71vzvNZiVLL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CPJGYK97?tag=values0d4-20",
        price: "$49.99",
        rating: 4.1,
        reviewCount: 1046,
      },
      {
        title: "GUCURIN Women Strapless Floral Dress with Sarf Mesh Tube Maxi Dress Summer Co...",
        image: "https://m.media-amazon.com/images/I/71zhmeSQkaL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F6MJ5WFQ?tag=values0d4-20",
        price: "$45.99",
        rating: 4,
        reviewCount: 168,
      },
    ],
  },
  {
    id: "winter-dresses",
    title: "Winter Wedding Guest Dresses",
    description: "Sophisticated dresses for winter wedding celebrations. Velvet, long sleeves, and dark tones that are perfect for colder months.",
    slug: "winter-wedding-guest-dresses",
    products: [
      {
        title: "ZESICA Women's Long Sleeve Floral Bodycon Dress 2026 Spring Fall Ruched Mesh ...",
        image: "https://m.media-amazon.com/images/I/617sy+YX12L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH5BTXXW?tag=values0d4-20",
        price: "$52.99",
        rating: 4.5,
        reviewCount: 649,
      },
      {
        title: "REORIA Long Sleeve Wedding Guest Maxi Dresses for Women Sheer Mesh Square Nec...",
        image: "https://m.media-amazon.com/images/I/610QlJ04yoL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH6PH41V?tag=values0d4-20",
        price: "$49.97",
        rating: 4.5,
        reviewCount: 500,
      },
      {
        title: "Verdusa Women's Floral Mesh Maxi Dresses Elegant Formal Long Sleeve Spring We...",
        image: "https://m.media-amazon.com/images/I/61NXa9j1ztL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F296GK7M?tag=values0d4-20",
        price: "$52.99",
        rating: 4.2,
        reviewCount: 330,
      },
      {
        title: "YMDUCH Women's Elegant Sleeveless Off Shoulder Bodycon Long Formal Party Even...",
        image: "https://m.media-amazon.com/images/I/511YfTNHu2L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B09VRN1NXL?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 8681,
      },
      {
        title: "ZESICA Women's Spring Floral Off Shoulder Bodycon Maxi Dresses 2026 Long Slee...",
        image: "https://m.media-amazon.com/images/I/61Idn8rOrRL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FG82KC42?tag=values0d4-20",
        price: "$49.99",
        rating: 4.4,
        reviewCount: 190,
      },
      {
        title: "ZESICA Women's 2026 Spring Long Sleeve Bodycon Dress Mock Neck Wedding Guest ...",
        image: "https://m.media-amazon.com/images/I/518jLGJrdqL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FCC4HW58?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 885,
      },
      {
        title: "Simplee Women’s V Neck Velvet Maxi Dress Short Sleeve Empire Waist Long Forma...",
        image: "https://m.media-amazon.com/images/I/614Yd7IDOIL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C862B6MZ?tag=values0d4-20",
        price: "$55.99",
        rating: 4.5,
        reviewCount: 2243,
      },
      {
        title: "BTFBM Women's Maxi Dresses Spring 2026 Long Sleeve Ruched Bodycon Solid Ruffl...",
        image: "https://m.media-amazon.com/images/I/61Ms7BP-WRL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FDKY3B76?tag=values0d4-20",
        price: "$49.98",
        rating: 4.4,
        reviewCount: 559,
      },
    ],
  },
];

// ─── BY DRESS CODE ──────────────────────────────────────────
export const dressCodeSections: HomepageSection[] = [
  {
    id: "black-tie-dresses",
    title: "Black Tie Wedding Guest Dresses",
    description: "Floor-length gowns and elegant formal dresses for the most upscale wedding celebrations. Look stunning in these sophisticated options.",
    slug: "black-tie-wedding-guest-dresses",
    products: [
      {
        title: "YMDUCH Women's Elegant Sleeveless Off Shoulder Bodycon Long Formal Party Even...",
        image: "https://m.media-amazon.com/images/I/511YfTNHu2L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B09VRWM82D?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 8681,
      },
      {
        title: "Memoriesea Women's Elegant Sleeveless High Neck Tie Cocktail Wedding Party Ma...",
        image: "https://m.media-amazon.com/images/I/51oQSnmj+hL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CQ27SRC6?tag=values0d4-20",
        price: "$46.99",
        rating: 4.3,
        reviewCount: 805,
      },
      {
        title: "Memoriesea Women's Sexy One Shoulder High Split Cocktail Wedding Party Maxi D...",
        image: "https://m.media-amazon.com/images/I/61vRQBC+arL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CB7L4R8Z?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 5749,
      },
      {
        title: "LAGSHIAN Women's Elegant Formal Long Dress One Shoulder Sleeveless Ruched Bod...",
        image: "https://m.media-amazon.com/images/I/512S0vLGDkL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CX56SF37?tag=values0d4-20",
        price: "$55.99",
        rating: 4.2,
        reviewCount: 985,
      },
      {
        title: "PRETTYGARDEN Wedding Guest Dresses for Women 2026 Summer Formal Gala Maxi Dre...",
        image: "https://m.media-amazon.com/images/I/61XkL86z-YL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DPKG3K8W?tag=values0d4-20",
        price: "$58.99",
        rating: 4.1,
        reviewCount: 507,
      },
      {
        title: "Memoriesea Women's Elegant Off Shoulder High Split Bodycon Evening Wedding Ma...",
        image: "https://m.media-amazon.com/images/I/51vRcyCcTtL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DRFFHT2K?tag=values0d4-20",
        price: "$51.99",
        rating: 4.2,
        reviewCount: 457,
      },
      {
        title: "EYNMIN Women's Sleeveless Bodycon Corset Maxi Dress Spaghetti Strap Ruched El...",
        image: "https://m.media-amazon.com/images/I/71aKcrvTrKL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F2693XQJ?tag=values0d4-20",
        price: "$68.99",
        rating: 4.3,
        reviewCount: 2227,
      },
      {
        title: "PRETTYGARDEN Cocktail Dresses for Women 2026 Summer Formal Elegant Tube Top S...",
        image: "https://m.media-amazon.com/images/I/61dXC66w14L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FQ9W6W7L?tag=values0d4-20",
        price: "$53.99",
        rating: 4,
        reviewCount: 95,
      },
    ],
  },
  {
    id: "formal-dresses",
    title: "Formal Wedding Guest Dresses",
    description: "Polished, elegant dresses for formal wedding ceremonies. Choose from refined midi and maxi styles that exude grace.",
    slug: "formal-wedding-guest-dresses",
    products: [
      {
        title: "YMDUCH Women's Elegant Sleeveless Off Shoulder Bodycon Long Formal Party Even...",
        image: "https://m.media-amazon.com/images/I/511YfTNHu2L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B09VRWM82D?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 8681,
      },
      {
        title: "KUTUMAI Off The Shoulder Maxi Long Dress Corset Ruched Bodycon Cocktail Forma...",
        image: "https://m.media-amazon.com/images/I/61iTzc-omrL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F4MLXFHF?tag=values0d4-20",
        price: "$63.99",
        rating: 4.4,
        reviewCount: 1015,
      },
      {
        title: "Long Black Formal Dresses for Women Gowns Evening Party Cocktail Dress,Split ...",
        image: "https://m.media-amazon.com/images/I/61wbcy3qmkL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C53BB6TH?tag=values0d4-20",
        price: "$32.03",
        rating: 4.5,
        reviewCount: 2823,
      },
      {
        title: "Memoriesea Women's Sexy One Shoulder High Split Cocktail Wedding Party Maxi D...",
        image: "https://m.media-amazon.com/images/I/61vRQBC+arL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CB7MJKY2?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 5749,
      },
      {
        title: "LAGSHIAN Women's Elegant Formal Long Dress One Shoulder Sleeveless Ruched Bod...",
        image: "https://m.media-amazon.com/images/I/51AJinmccaL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FGTV5Z1S?tag=values0d4-20",
        price: "$55.99",
        rating: 4.2,
        reviewCount: 985,
      },
      {
        title: "Ekaliy Women's One Shoulder Belted Maxi Dress Long Formal Wedding Guest Dress...",
        image: "https://m.media-amazon.com/images/I/61EILtJ9Z4L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F9W6TLLW?tag=values0d4-20",
        price: "$54.99",
        rating: 4,
        reviewCount: 285,
      },
      {
        title: "MUSHARE Women's Halter Neck Sexy Split Cocktail Party Maxi Long Formal Dress",
        image: "https://m.media-amazon.com/images/I/51127-FIgiL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BC1GMV44?tag=values0d4-20",
        price: "$59.99",
        rating: 4.4,
        reviewCount: 2944,
      },
      {
        title: "Popilush Womens Shapewear Maxi Dress Multi Way Wear Off The Shoulder Bodycon ...",
        image: "https://m.media-amazon.com/images/I/716hwmKHdYL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0D8PSWB98?tag=values0d4-20",
        price: "$129.99",
        rating: 4,
        reviewCount: 546,
      },
    ],
  },
  {
    id: "semi-formal-dresses",
    title: "Semi-Formal Wedding Guest Dresses",
    description: "Versatile dresses that strike the perfect balance between dressy and relaxed. Ideal for most wedding celebrations.",
    slug: "semi-formal-wedding-guest-dresses",
    products: [
      {
        title: "Long Black Formal Dresses for Women Gowns Evening Party Cocktail Dress,Split ...",
        image: "https://m.media-amazon.com/images/I/61wbcy3qmkL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C53BB6TH?tag=values0d4-20",
        price: "$32.03",
        rating: 4.5,
        reviewCount: 2823,
      },
      {
        title: "BTFBM Women Summer Floral Maxi Dresses Elegant Spaghetti Strap Dress Printed ...",
        image: "https://m.media-amazon.com/images/I/71gem062CHL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DP6ZZY1D?tag=values0d4-20",
        price: "$46.99",
        rating: 4.5,
        reviewCount: 1526,
      },
      {
        title: "Bbonlinedress Halter Cocktail Women Dresses Prom Formal Wedding Guest Bridesm...",
        image: "https://m.media-amazon.com/images/I/61Fn3Q95k2L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CSYDZT53?tag=values0d4-20",
        price: "$46.54",
        rating: 4.4,
        reviewCount: 964,
      },
      {
        title: "Holipick Women's Cocktail Dresses Wedding Guest Party Crew Neck Short A Line ...",
        image: "https://m.media-amazon.com/images/I/61n82NuT7IL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F47ZQVQT?tag=values0d4-20",
        price: "$47.99",
        rating: 4.1,
        reviewCount: 496,
      },
      {
        title: "Verdusa Women's Formal Wedding Guest Dress Halter Flowy Chiffon Asymmetrical ...",
        image: "https://m.media-amazon.com/images/I/51RVhLZ0X0L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CP3XT3R5?tag=values0d4-20",
        price: "$45.99",
        rating: 4.2,
        reviewCount: 769,
      },
      {
        title: "ZESICA Women's Long Sleeve Floral Bodycon Dress 2026 Spring Fall Ruched Mesh ...",
        image: "https://m.media-amazon.com/images/I/617sy+YX12L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH57DGCK?tag=values0d4-20",
        price: "$52.99",
        rating: 4.5,
        reviewCount: 649,
      },
      {
        title: "Ekaliy Women's One Shoulder Belted Maxi Dress Long Formal Wedding Guest Dress...",
        image: "https://m.media-amazon.com/images/I/51F48iZSHML._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F9W7PTN9?tag=values0d4-20",
        price: "$54.99",
        rating: 4,
        reviewCount: 285,
      },
      {
        title: "DRESSTELLS Women's Cocktail Dresses 2026, Formal Wedding Guest Prom Party Eve...",
        image: "https://m.media-amazon.com/images/I/61H+hpkSMKL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CHRW1BV9?tag=values0d4-20",
        price: "$45.99",
        rating: 4.2,
        reviewCount: 1169,
      },
    ],
  },
  {
    id: "cocktail-dresses",
    title: "Cocktail Wedding Guest Dresses",
    description: "Chic knee-length and midi cocktail dresses. Perfect for evening receptions and celebrations that call for something special.",
    slug: "cocktail-wedding-guest-dresses",
    products: [
      {
        title: "ZESICA Women's Summer Short Sleeve Floral Bodycon Dress 2026 Ruched Mesh Wedd...",
        image: "https://m.media-amazon.com/images/I/71lDmsv+04L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0G3P62SJ7?tag=values0d4-20",
        price: "$48.99",
        rating: 4.5,
        reviewCount: 83,
      },
      {
        title: "KUTUMAI Off The Shoulder Maxi Long Dress Corset Ruched Bodycon Cocktail Forma...",
        image: "https://m.media-amazon.com/images/I/71saPb5Lo6L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DZN5WK27?tag=values0d4-20",
        price: "$64.99",
        rating: 4.4,
        reviewCount: 1015,
      },
      {
        title: "Long Black Formal Dresses for Women Gowns Evening Party Cocktail Dress,Split ...",
        image: "https://m.media-amazon.com/images/I/61wbcy3qmkL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C53FB542?tag=values0d4-20",
        price: "$59.78",
        rating: 4.5,
        reviewCount: 2823,
      },
      {
        title: "ZESICA Women's Summer Strapless Floral Midi Dress 2026 Bodycon Mesh Tube Wedd...",
        image: "https://m.media-amazon.com/images/I/71UczIhC4bL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FXWCV32B?tag=values0d4-20",
        price: "$58.99",
        rating: 4.6,
        reviewCount: 102,
      },
      {
        title: "Memoriesea Women's Sexy One Shoulder High Split Cocktail Wedding Party Maxi D...",
        image: "https://m.media-amazon.com/images/I/61HuqZJkSqL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CN65T7PQ?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 5749,
      },
      {
        title: "ZESICA Women's 2026 Summer Ruched Bodycon Dress Sleeveless Backless Ruffle Me...",
        image: "https://m.media-amazon.com/images/I/61wEgCVOEfL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CRRFFLYS?tag=values0d4-20",
        price: "$52.99",
        rating: 4.2,
        reviewCount: 815,
      },
      {
        title: "ZESICA Women's 2026 Spring Long Sleeve Bodycon Dress Mock Neck Wedding Guest ...",
        image: "https://m.media-amazon.com/images/I/51d1P544JiL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FCC21WWB?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 885,
      },
      {
        title: "ZESICA Women's 2026 Summer Sleeveless Halter Neck Ruffle Tiered Layed Chiffon...",
        image: "https://m.media-amazon.com/images/I/71bJaG7lpAL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BS3HBNHW?tag=values0d4-20",
        price: "$59.99",
        rating: 4.4,
        reviewCount: 3196,
      },
    ],
  },
  {
    id: "casual-dresses",
    title: "Casual Wedding Guest Dresses",
    description: "Relaxed yet stylish dresses for casual and outdoor weddings. Comfortable enough to dance in, pretty enough to photograph beautifully.",
    slug: "casual-wedding-guest-dresses",
    products: [
      {
        title: "PRETTYGARDEN Women's 2026 Summer Satin Dress Elegant Sleeveless Mock Neck Coc...",
        image: "https://m.media-amazon.com/images/I/51KBy6HsbSL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BRSFKFJ4?tag=values0d4-20",
        price: "$57.99",
        rating: 4,
        reviewCount: 4726,
      },
      {
        title: "Simplee Womens Floral Maxi Dress Short Sleeve Summer Boho Wedding Guest Dress...",
        image: "https://m.media-amazon.com/images/I/71jW7X+kpCL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DPJ8Q3CN?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 579,
      },
      {
        title: "ZESICA Women's Long Sleeve Floral Bodycon Dress 2026 Spring Fall Ruched Mesh ...",
        image: "https://m.media-amazon.com/images/I/610r9KEpseL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH5C2QRD?tag=values0d4-20",
        price: "$41.99",
        rating: 4.5,
        reviewCount: 649,
      },
      {
        title: "CUPSHE Women's Mini Dresses Casual Spring V Neck Chiffon Long Peasant Sleeves...",
        image: "https://m.media-amazon.com/images/I/71CwKwMLckL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BCL4R2LT?tag=values0d4-20",
        price: "$45.99",
        rating: 4.1,
        reviewCount: 4619,
      },
      {
        title: "BTFBM Women Summer Bohemian Floral Casual Wrap V Neck Ruffle Cap Sleeveless B...",
        image: "https://m.media-amazon.com/images/I/61d5+jUT-UL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B091CLWZZB?tag=values0d4-20",
        price: "$44.99",
        rating: 4.2,
        reviewCount: 17031,
      },
      {
        title: "Annebouti Women 2026 Summer Spring Ruched Maxi Dress Adjustable Spaghetti Str...",
        image: "https://m.media-amazon.com/images/I/713aR3oGojL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DYF3GC6L?tag=values0d4-20",
        price: "$35.99",
        rating: 4.5,
        reviewCount: 903,
      },
      {
        title: "PRETTYGARDEN Womens Spring Dresses 2026 Casual Sleeveless Crewneck Aline Maxi...",
        image: "https://m.media-amazon.com/images/I/616v2WHxAWL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F2YT2727?tag=values0d4-20",
        price: "$46.98",
        rating: 4.3,
        reviewCount: 377,
      },
      {
        title: "PRETTYGARDEN Summer Dresses for Women 2026 Elegant Classy Spring A Line Busin...",
        image: "https://m.media-amazon.com/images/I/71RioH+ltvL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F4N181T2?tag=values0d4-20",
        price: "$39.99",
        rating: 4.4,
        reviewCount: 814,
      },
    ],
  },
  {
    id: "best-dresses",
    title: "Best Wedding Guest Dresses",
    description: "Our top-rated picks across all styles. Every dress here is 4.5+ stars with verified reviews — the best of the best for any wedding.",
    slug: "best-wedding-guest-dresses",
    products: [
      {
        title: "Women's Mock Neck Sleeveless Mesh Back Slit Ruched Bodycon Wedding Guest Cock...",
        image: "https://m.media-amazon.com/images/I/51Wp0-hI+ZL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FF98SZNK?tag=values0d4-20",
        price: "$38.99",
        rating: 4.9,
        reviewCount: 50,
      },
      {
        title: "Long Sleeve Dress for Women Floral Print Ruched Wedding Guest Maxi Dresses T...",
        image: "https://m.media-amazon.com/images/I/61855ie5HaL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DHZVQJRQ?tag=values0d4-20",
        price: "$14.99",
        rating: 4.8,
        reviewCount: 159,
      },
      {
        title: "Women's Floral Strapless Maxi Dress 2026 Summer Mesh Tube Bodycon Formal Wed...",
        image: "https://m.media-amazon.com/images/I/719ZTR5EXFL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FX2TCN54?tag=values0d4-20",
        price: "$57.99",
        rating: 4.8,
        reviewCount: 93,
      },
      {
        title: "Women's Long Sleeve Bodycon Dresses 2026 Spring Sexy Floral Mesh Slit Ruched...",
        image: "https://m.media-amazon.com/images/I/71lKzgHerbL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FCBTJKK2?tag=values0d4-20",
        price: "$34.99",
        rating: 4.8,
        reviewCount: 130,
      },
      {
        title: "Womens Boat Neck Formal Bodycon Maxi Sleeveless Slim Fitted Wedding Guest Lo...",
        image: "https://m.media-amazon.com/images/I/61L0MJCO+9L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FPLD3L9M?tag=values0d4-20",
        price: "$46.69",
        rating: 4.9,
        reviewCount: 31,
      },
      {
        title: "Women Summer Strapless Maxi Dress 2026 Bodycon Floral Long Wedding Guest Dre...",
        image: "https://m.media-amazon.com/images/I/61rAayUfb6L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DP21T5Z7?tag=values0d4-20",
        price: "$26.99",
        rating: 4.7,
        reviewCount: 254,
      },
      {
        title: "Velvet Wedding Guest Dress - Fall Formal Holiday V Neck Empire Waist Long Dre...",
        image: "https://m.media-amazon.com/images/I/71hmpq0ULML._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DGQLPQK2?tag=values0d4-20",
        price: "$60.99",
        rating: 4.7,
        reviewCount: 137,
      },
      {
        title: "Women's Sleeveless Floral Bodycon Maxi Dress 2026 Summer Ruched Mesh Wedding...",
        image: "https://m.media-amazon.com/images/I/61Mt1MEPr9L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0G4TWLQTW?tag=values0d4-20",
        price: "$45.99",
        rating: 4.8,
        reviewCount: 44,
      },
    ],
  },
  {
    id: "elegant-dresses",
    title: "Elegant Wedding Guest Dresses",
    description: "Refined, sophisticated styles for women who want to look effortlessly polished. Perfect for formal and semi-formal weddings.",
    slug: "elegant-wedding-guest-dresses",
    products: [
      {
        title: "Womens Elegant Halter Neck Formal Bodycon Fitted Wedding Guest Long Cocktail...",
        image: "https://m.media-amazon.com/images/I/71coGjnN5BL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0GJ2LVQ2Y?tag=values0d4-20",
        price: "$48.99",
        rating: 4.8,
        reviewCount: 35,
      },
      {
        title: "Women's Elegant Floral Bodycon Maxi Dress Formal Long Sleeve Mock Neck Weddi...",
        image: "https://m.media-amazon.com/images/I/51igHU2IFJL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FM7RXKCP?tag=values0d4-20",
        price: "$19.99",
        rating: 4.8,
        reviewCount: 32,
      },
      {
        title: "Women's Floral Strapless Maxi Dress 2026 Summer Mesh Tube Bodycon Formal Wed...",
        image: "https://m.media-amazon.com/images/I/71PDkhV4UoL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FX2RP6NN?tag=values0d4-20",
        price: "$57.99",
        rating: 4.8,
        reviewCount: 93,
      },
      {
        title: "Womens Sparkly Lace Appliques Chiffon Prom Dresses V-Neck Spaghetti Straps F...",
        image: "https://m.media-amazon.com/images/I/61T8YCSJaUL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DQ3L8BPG?tag=values0d4-20",
        price: "$84.99",
        rating: 4.9,
        reviewCount: 34,
      },
      {
        title: "Womens Boat Neck Formal Bodycon Maxi Sleeveless Slim Fitted Wedding Guest Lo...",
        image: "https://m.media-amazon.com/images/I/61SpS6x0CmL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FPQ9NNQF?tag=values0d4-20",
        price: "$46.69",
        rating: 4.9,
        reviewCount: 31,
      },
      {
        title: "Womens Off The Shoulder Wedding Guest Maxi Long Dress 2026 Sexy Mesh One Sho...",
        image: "https://m.media-amazon.com/images/I/71yStoHNIlL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FLDS2Z4F?tag=values0d4-20",
        price: "$29.99",
        rating: 4.8,
        reviewCount: 31,
      },
      {
        title: "Women's Fall Off Shoulder Floral Maxi Dresses Formal Long Sleeve Bodycon Coc...",
        image: "https://m.media-amazon.com/images/I/61BkDrZjF1L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FBR47JPL?tag=values0d4-20",
        price: "$35.99",
        rating: 4.6,
        reviewCount: 304,
      },
      {
        title: "Off The Shoulder Bridesmaid Dresses with Pockets Ruched Chiffon Long Slit Fo...",
        image: "https://m.media-amazon.com/images/I/71-0ycolLxL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C4Y57FP7?tag=values0d4-20",
        price: "$59.99",
        rating: 4.6,
        reviewCount: 157,
      },
    ],
  },
];

// ─── BY COLOR ────────────────────────────────────────────
export const colorSections: HomepageSection[] = [
  {
    id: "black-dresses",
    title: "Black Wedding Guest Dresses",
    description: "Timeless and sophisticated, black dresses are always a safe and stylish choice for wedding celebrations.",
    slug: "black-wedding-guest-dresses",
    products: [
      {
        title: "Memoriesea Women's Sexy One Shoulder High Split Cocktail Wedding Party Maxi D...",
        image: "https://m.media-amazon.com/images/I/61vRQBC+arL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CB7MJKY2?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 5749,
      },
      {
        title: "YMDUCH Women's Elegant Sleeveless Off Shoulder Bodycon Long Formal Party Even...",
        image: "https://m.media-amazon.com/images/I/511YfTNHu2L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B09VRWM82D?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 8681,
      },
      {
        title: "PRETTYGARDEN Women's Summer One Shoulder Long Formal Dresses Sleeveless Ruche...",
        image: "https://m.media-amazon.com/images/I/61CkyHi94sL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B09YTVKBQ1?tag=values0d4-20",
        price: "$66.99",
        rating: 4.2,
        reviewCount: 3193,
      },
      {
        title: "Long Black Formal Dresses for Women Gowns Evening Party Cocktail Dress,Split ...",
        image: "https://m.media-amazon.com/images/I/61wbcy3qmkL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C53FB542?tag=values0d4-20",
        price: "$59.78",
        rating: 4.5,
        reviewCount: 2823,
      },
      {
        title: "Memoriesea Women's Sexy High Split Sleeveless Backless Party Wedding Maxi Dress",
        image: "https://m.media-amazon.com/images/I/512MajSR6WL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0D7W35Q51?tag=values0d4-20",
        price: "$51.99",
        rating: 4.2,
        reviewCount: 252,
      },
      {
        title: "HOCILLE Women's Sexy V Neck Backless Bodycon Spaghetti Strap Elegant Ruffle M...",
        image: "https://m.media-amazon.com/images/I/618fDTG-V4L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F13P693V?tag=values0d4-20",
        price: "$46.99",
        rating: 4.4,
        reviewCount: 515,
      },
      {
        title: "ZESICA Women's Summer Sleeveless Halter Midi Dress 2026 Off Shoulder High Wai...",
        image: "https://m.media-amazon.com/images/I/51oz3E7J01L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DSVLWX75?tag=values0d4-20",
        price: "$50.99",
        rating: 4.1,
        reviewCount: 615,
      },
      {
        title: "MEROKEETY Women's Sleeveless Lace Floral Elegant Cocktail Dress Crew Neck Kne...",
        image: "https://m.media-amazon.com/images/I/61GAi4F7LzS._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B01N1WFB1F?tag=values0d4-20",
        price: "$69.99",
        rating: 4.4,
        reviewCount: 20809,
      },
    ],
  },
  {
    id: "blue-dresses",
    title: "Blue Wedding Guest Dresses",
    description: "From royal blue to powder blue, these stunning blue dresses make a beautiful statement at any wedding ceremony.",
    slug: "blue-wedding-guest-dresses",
    products: [
      {
        title: "ZESICA Women's Summer Sleeveless Halter Midi Dress 2026 Off Shoulder High Wai...",
        image: "https://m.media-amazon.com/images/I/51CDt4vL5yL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DSVLRJDF?tag=values0d4-20",
        price: "$53.99",
        rating: 4.1,
        reviewCount: 615,
      },
      {
        title: "Long Black Formal Dresses for Women Gowns Evening Party Cocktail Dress,Split ...",
        image: "https://m.media-amazon.com/images/I/61vozf6iodL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C53BK6S9?tag=values0d4-20",
        price: "$58.78",
        rating: 4.5,
        reviewCount: 2823,
      },
      {
        title: "ZESICA Women's Summer Strapless Floral Midi Dress 2026 Bodycon Mesh Tube Wedd...",
        image: "https://m.media-amazon.com/images/I/71UczIhC4bL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FXWCKFRG?tag=values0d4-20",
        price: "$58.99",
        rating: 4.6,
        reviewCount: 102,
      },
      {
        title: "PRETTYGARDEN Women's 2026 Summer Wedding Guest Dress Sleeveless Ruffle Formal...",
        image: "https://m.media-amazon.com/images/I/61wTcfcGJcL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DHR98BQ5?tag=values0d4-20",
        price: "$35.98",
        rating: 4.3,
        reviewCount: 1462,
      },
      {
        title: "BTFBM Cocktail Dresses for Women Satin Silk Sleeveless Mock Neck High Waist M...",
        image: "https://m.media-amazon.com/images/I/51FiO191PsL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BRP56168?tag=values0d4-20",
        price: "$54.99",
        rating: 4.1,
        reviewCount: 1854,
      },
      {
        title: "ZESICA Women's Long Sleeve Floral Bodycon Dress 2026 Spring Fall Ruched Mesh ...",
        image: "https://m.media-amazon.com/images/I/617sy+YX12L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH57DGCK?tag=values0d4-20",
        price: "$52.99",
        rating: 4.5,
        reviewCount: 649,
      },
      {
        title: "PRETTYGARDEN Women's Smocked Midi Tulle Dress 2026 Summer Puffy Short Sleeve ...",
        image: "https://m.media-amazon.com/images/I/71ie0TDdDGL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DJNVSQSH?tag=values0d4-20",
        price: "$57.99",
        rating: 4.4,
        reviewCount: 1148,
      },
      {
        title: "ZESICA Women's Summer Strapless Bodycon Maxi Dress 2026 Ribbed Knit Backless ...",
        image: "https://m.media-amazon.com/images/I/51hGfoCBCNL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DZCZ9MVM?tag=values0d4-20",
        price: "$50.99",
        rating: 4.2,
        reviewCount: 401,
      },
    ],
  },
  {
    id: "navy-dresses",
    title: "Navy Wedding Guest Dresses",
    description: "Classic and universally flattering, navy dresses bring quiet elegance to every wedding occasion.",
    slug: "navy-wedding-guest-dresses",
    products: [
      {
        title: "Memoriesea Women's Elegant Sleeveless High Neck Tie Cocktail Wedding Party Ma...",
        image: "https://m.media-amazon.com/images/I/51FHF-TUweL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DGDWNJ4S?tag=values0d4-20",
        price: "$46.99",
        rating: 4.3,
        reviewCount: 805,
      },
      {
        title: "KUTUMAI Off The Shoulder Maxi Long Dress Corset Ruched Bodycon Cocktail Forma...",
        image: "https://m.media-amazon.com/images/I/61-ZcdadDPL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F7DLTFH3?tag=values0d4-20",
        price: "$63.99",
        rating: 4.4,
        reviewCount: 1015,
      },
      {
        title: "YMDUCH Women's Elegant Sleeveless Off Shoulder Bodycon Long Formal Party Even...",
        image: "https://m.media-amazon.com/images/I/51ZshvsJ3tL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BN2T86LW?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 8681,
      },
      {
        title: "PRETTYGARDEN Women's 2026 Summer Wedding Guest Dress Sleeveless Ruffle Formal...",
        image: "https://m.media-amazon.com/images/I/61wTcfcGJcL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DHR98BQ5?tag=values0d4-20",
        price: "$35.98",
        rating: 4.3,
        reviewCount: 1462,
      },
      {
        title: "Long Black Formal Dresses for Women Gowns Evening Party Cocktail Dress,Split ...",
        image: "https://m.media-amazon.com/images/I/61vozf6iodL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C53BK6S9?tag=values0d4-20",
        price: "$58.78",
        rating: 4.5,
        reviewCount: 2823,
      },
      {
        title: "Memoriesea Women's Sexy One Shoulder High Split Cocktail Wedding Party Maxi D...",
        image: "https://m.media-amazon.com/images/I/61Zw7ciCF6L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CSJWPLZ7?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 5749,
      },
      {
        title: "Realtix Satin Silk Backless Tube Tops Maxi Dress for Women Low Back Hollow Ou...",
        image: "https://m.media-amazon.com/images/I/41VHinm9ddL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BV5WXP7R?tag=values0d4-20",
        price: "$44.99",
        rating: 4.2,
        reviewCount: 2206,
      },
      {
        title: "PRETTYGARDEN Women's Summer One Shoulder Long Formal Dresses Sleeveless Ruche...",
        image: "https://m.media-amazon.com/images/I/61OF99wgmjL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BGPJGPLT?tag=values0d4-20",
        price: "$55.99",
        rating: 4.2,
        reviewCount: 3193,
      },
    ],
  },
  {
    id: "green-dresses",
    title: "Green Wedding Guest Dresses",
    description: "Emerald, sage, olive, and forest green — green dresses bring a fresh and nature-inspired look to any wedding.",
    slug: "green-wedding-guest-dresses",
    products: [
      {
        title: "Memoriesea Women's Sexy One Shoulder High Split Cocktail Wedding Party Maxi D...",
        image: "https://m.media-amazon.com/images/I/61HuqZJkSqL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CN65RTCF?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 5749,
      },
      {
        title: "Ekaliy Women's One Shoulder Belted Maxi Dress Long Formal Wedding Guest Dress...",
        image: "https://m.media-amazon.com/images/I/61EILtJ9Z4L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F9W6TLLW?tag=values0d4-20",
        price: "$54.99",
        rating: 4,
        reviewCount: 285,
      },
      {
        title: "PRETTYGARDEN Cocktail Dresses for Women 2026 Summer Formal Elegant Tube Top S...",
        image: "https://m.media-amazon.com/images/I/61lcnCd1iQL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FQ9JYSS6?tag=values0d4-20",
        price: "$54.99",
        rating: 4,
        reviewCount: 95,
      },
      {
        title: "72styles Infinity Dress with Bandeau, Convertible Bridesmaid Dress, Long, Plu...",
        image: "https://m.media-amazon.com/images/I/61OnjLS5gjL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B08SQMLG2R?tag=values0d4-20",
        price: "$52.99",
        rating: 4.4,
        reviewCount: 17300,
      },
      {
        title: "PRETTYGARDEN Women's 2026 Spring Floral Spaghetti Strap Maxi Dress Stretch Se...",
        image: "https://m.media-amazon.com/images/I/61M7t3v6iUL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CNP4N39J?tag=values0d4-20",
        price: "$39.98",
        rating: 4.5,
        reviewCount: 1340,
      },
      {
        title: "MUSHARE Women's Halter Neck Sexy Split Cocktail Party Maxi Long Formal Dress",
        image: "https://m.media-amazon.com/images/I/61G8RF1nKaL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BKB56DM3?tag=values0d4-20",
        price: "$59.99",
        rating: 4.4,
        reviewCount: 2944,
      },
      {
        title: "Dokuritu Women's Beach Crochet Lace Maxi Dress Solid Color Summer Vacation Sp...",
        image: "https://m.media-amazon.com/images/I/71a9DnwsPuL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B09L8MPCYN?tag=values0d4-20",
        price: "$45.99",
        rating: 4.2,
        reviewCount: 7656,
      },
      {
        title: "PRETTYGARDEN Women's 2026 Summer Wedding Guest Dress Sleeveless Ruffle Formal...",
        image: "https://m.media-amazon.com/images/I/615Wz2ZMRPL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CNSHGLR1?tag=values0d4-20",
        price: "$35.99",
        rating: 4.3,
        reviewCount: 1462,
      },
    ],
  },
  {
    id: "pink-dresses",
    title: "Pink Wedding Guest Dresses",
    description: "Romantic and feminine, pink dresses range from soft blush to vibrant hot pink — perfect for spring and summer weddings.",
    slug: "pink-wedding-guest-dresses",
    products: [
      {
        title: "PRETTYGARDEN Women's 2026 Summer Wedding Guest Dress Sleeveless Ruffle Formal...",
        image: "https://m.media-amazon.com/images/I/619jq8G6lVL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CNSGYGMW?tag=values0d4-20",
        price: "$59.99",
        rating: 4.3,
        reviewCount: 1462,
      },
      {
        title: "LAGSHIAN Women's Elegant Formal Long Dress One Shoulder Sleeveless Ruched Bod...",
        image: "https://m.media-amazon.com/images/I/51mnGpkYStL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CX4TVHXC?tag=values0d4-20",
        price: "$55.99",
        rating: 4.2,
        reviewCount: 985,
      },
      {
        title: "GORGLITTER Women's Floral Summer Wedding Guest Dress Ruched Cocktail Party Br...",
        image: "https://m.media-amazon.com/images/I/614-PtyD+UL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DPLZVN4C?tag=values0d4-20",
        price: "$52.99",
        rating: 4.4,
        reviewCount: 240,
      },
      {
        title: "KUTUMAI Off The Shoulder Maxi Long Dress Corset Ruched Bodycon Cocktail Forma...",
        image: "https://m.media-amazon.com/images/I/6120-W4BmJL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F48SC5W5?tag=values0d4-20",
        price: "$63.99",
        rating: 4.4,
        reviewCount: 1015,
      },
      {
        title: "ZESICA Women's Summer Strapless Bodycon Maxi Dress 2026 Ribbed Knit Backless ...",
        image: "https://m.media-amazon.com/images/I/51k0gv0-7rL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DZD3YLMH?tag=values0d4-20",
        price: "$53.99",
        rating: 4.2,
        reviewCount: 401,
      },
      {
        title: "Dokotoo Women's Wrap V Neck Short Flared Sleeve Wedding Guest Dress Smocked E...",
        image: "https://m.media-amazon.com/images/I/61c-syWY8vL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DJZHP68J?tag=values0d4-20",
        price: "$49.99",
        rating: 4.1,
        reviewCount: 1732,
      },
      {
        title: "VOUIAO Women's 2026 Spring Formal Evening Gown Elegant Long Prom Dress Weddin...",
        image: "https://m.media-amazon.com/images/I/61-D+pHd+TL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FJLSQ7ZK?tag=values0d4-20",
        price: "$49.99",
        rating: 4.1,
        reviewCount: 183,
      },
      {
        title: "ZESICA Women's Summer Short Sleeve Bodycon Midi Dress 2026 Spring Elegant For...",
        image: "https://m.media-amazon.com/images/I/61PRD-3IY3L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FXQMK6QB?tag=values0d4-20",
        price: "$55.99",
        rating: 4.5,
        reviewCount: 74,
      },
    ],
  },
  {
    id: "yellow-dresses",
    title: "Yellow Wedding Guest Dresses",
    description: "Bright and cheerful yellow dresses bring sunny energy to wedding celebrations. A bold and beautiful choice.",
    slug: "yellow-wedding-guest-dresses",
    products: [
      {
        title: "KUTUMAI Off The Shoulder Maxi Long Dress Corset Ruched Bodycon Cocktail Forma...",
        image: "https://m.media-amazon.com/images/I/61iTzc-omrL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F4MLXFHF?tag=values0d4-20",
        price: "$63.99",
        rating: 4.4,
        reviewCount: 1015,
      },
      {
        title: "PRETTYGARDEN Women Summer Strapless Maxi Dress Bodycon Floral Sexy Long Weddi...",
        image: "https://m.media-amazon.com/images/I/612KDF3RwyL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F221LKK6?tag=values0d4-20",
        price: "$34.89",
        rating: 4.5,
        reviewCount: 721,
      },
      {
        title: "Women Sexy V Neck Sleeveless Mesh Ruffle Hem Bodycon Maxi Casual Backless Hig...",
        image: "https://m.media-amazon.com/images/I/51Rvv3xV60L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DCVPKW7H?tag=values0d4-20",
        price: "$40.49",
        rating: 4.2,
        reviewCount: 1107,
      },
      {
        title: "GUCURIN Women Strapless Floral Dress with Sarf Mesh Tube Maxi Dress Summer Co...",
        image: "https://m.media-amazon.com/images/I/518gQ+lqRAL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F9WS3WKP?tag=values0d4-20",
        price: "$45.99",
        rating: 4,
        reviewCount: 168,
      },
      {
        title: "2026 Satin One Shoulder Maxi Dress for Women Summer Silk Formal Elegant Backl...",
        image: "https://m.media-amazon.com/images/I/61KL1077XYL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DP2GNYTG?tag=values0d4-20",
        price: "$49.99",
        rating: 4,
        reviewCount: 162,
      },
      {
        title: "HTZMO Women Elegant Summer Bodycon Maxi Dress Halter Neck Formal Wedding Gues...",
        image: "https://m.media-amazon.com/images/I/51QfN1F2NjL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F67358HY?tag=values0d4-20",
        price: "$61.99",
        rating: 4.2,
        reviewCount: 365,
      },
      {
        title: "PRETTYGARDEN Women's Summer Maxi Floral Dresses Ruched Bodycon Sleeveless Mes...",
        image: "https://m.media-amazon.com/images/I/6141fD0j0AL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F213NKDV?tag=values0d4-20",
        price: "$37.99",
        rating: 4.6,
        reviewCount: 507,
      },
      {
        title: "Pungdra Women's Sexy V Neck Mesh Ruffles Hem High Slit Bodycon Maxi Dress for...",
        image: "https://m.media-amazon.com/images/I/51k9nq8w4xL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F1F81V43?tag=values0d4-20",
        price: "$42.99",
        rating: 4.2,
        reviewCount: 184,
      },
    ],
  },
  {
    id: "burgundy-dresses",
    title: "Burgundy Wedding Guest Dresses",
    description: "Deep, rich burgundy dresses are perfect for fall and winter weddings. This luxurious color flatters every skin tone.",
    slug: "burgundy-wedding-guest-dresses",
    products: [
      {
        title: "MEROKEETY Women's Floral Strapless Maxi Dress 2026 Summer Mesh Tube Bodycon F...",
        image: "https://m.media-amazon.com/images/I/71PDkhV4UoL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FX2P7KSR?tag=values0d4-20",
        price: "$57.99",
        rating: 4.8,
        reviewCount: 89,
      },
      {
        title: "Memoriesea Women's Elegant Sleeveless One Shoulder Bodycon Evening Cocktail M...",
        image: "https://m.media-amazon.com/images/I/51fhUkfrVtL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FWQZKY5T?tag=values0d4-20",
        price: "$48.99",
        rating: 4.2,
        reviewCount: 314,
      },
      {
        title: "Memoriesea Women's Elegant Off Shoulder High Split Bodycon Evening Wedding Ma...",
        image: "https://m.media-amazon.com/images/I/515quu+toIL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FHWDPPD2?tag=values0d4-20",
        price: "$51.99",
        rating: 4.2,
        reviewCount: 457,
      },
      {
        title: "Memoriesea Women's Elegant Sleeveless High Neck Tie Cocktail Wedding Party Ma...",
        image: "https://m.media-amazon.com/images/I/51wvh7r5b2L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DP5CH8SZ?tag=values0d4-20",
        price: "$46.99",
        rating: 4.3,
        reviewCount: 805,
      },
      {
        title: "Memoriesea Women's Sexy One Shoulder High Split Cocktail Wedding Party Maxi D...",
        image: "https://m.media-amazon.com/images/I/61Vp4LCVqjL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CN66K2BD?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 5749,
      },
      {
        title: "Long Black Formal Dresses for Women Gowns Evening Party Cocktail Dress,Split ...",
        image: "https://m.media-amazon.com/images/I/61-E9t9ojeL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C539XVWV?tag=values0d4-20",
        price: "$58.78",
        rating: 4.5,
        reviewCount: 2823,
      },
      {
        title: "Memoriesea Women's Sexy Plunge Neckline Bodycon Ruched High Slit Party Maxi D...",
        image: "https://m.media-amazon.com/images/I/51c2zIhPLmL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FP4F8V32?tag=values0d4-20",
        price: "$43.99",
        rating: 4.4,
        reviewCount: 245,
      },
      {
        title: "PRETTYGARDEN Cocktail Dresses for Women 2026 Summer Formal Elegant Tube Top S...",
        image: "https://m.media-amazon.com/images/I/6135Oh6gJWL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FQ9QHBHH?tag=values0d4-20",
        price: "$53.99",
        rating: 4,
        reviewCount: 95,
      },
    ],
  },
  {
    id: "brown-dresses",
    title: "Brown Wedding Guest Dresses",
    description: "Warm and earthy, brown dresses offer a unique and chic alternative. From chocolate to terracotta, these tones are on trend.",
    slug: "brown-wedding-guest-dresses",
    products: [
      {
        title: "Memoriesea Women's Sexy One Shoulder High Split Cocktail Wedding Party Maxi D...",
        image: "https://m.media-amazon.com/images/I/61Q1HMdf7rL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0D3FD5S5B?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 5749,
      },
      {
        title: "HTZMO Women Elegant Summer Bodycon Maxi Dress Halter Neck Formal Wedding Gues...",
        image: "https://m.media-amazon.com/images/I/51aw06CzkZL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F1ZW91FG?tag=values0d4-20",
        price: "$61.99",
        rating: 4.2,
        reviewCount: 365,
      },
      {
        title: "REORIA Women's Fall Mesh Sheer Long Sleeve Midi Ruched Bodycon Dress Mock Nec...",
        image: "https://m.media-amazon.com/images/I/51vGGi9xm0L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FKTFJF68?tag=values0d4-20",
        price: "$49.97",
        rating: 4.6,
        reviewCount: 190,
      },
      {
        title: "ZESICA Women's 2026 Spring Long Sleeve Bodycon Dress Mock Neck Wedding Guest ...",
        image: "https://m.media-amazon.com/images/I/518jLGJrdqL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FCC4HW58?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 885,
      },
      {
        title: "BTFBM Summer Maxi Dresses for Women 2026 Strapless Ruched Tube Top Beach Vaca...",
        image: "https://m.media-amazon.com/images/I/51ykKnAzpQL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DMVV1F8Z?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 213,
      },
      {
        title: "REORIA Long Sleeve Wedding Guest Maxi Dresses for Women Sheer Mesh Square Nec...",
        image: "https://m.media-amazon.com/images/I/61f9dFkDNYL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH6PCDPJ?tag=values0d4-20",
        price: "$49.97",
        rating: 4.5,
        reviewCount: 500,
      },
      {
        title: "HOCILLE Women's Sexy V Neck Backless Bodycon Spaghetti Strap Elegant Ruffle M...",
        image: "https://m.media-amazon.com/images/I/61D5kYupDfL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FQ1ZDQ7B?tag=values0d4-20",
        price: "$48.99",
        rating: 4.4,
        reviewCount: 515,
      },
      {
        title: "PRETTYGARDEN Womens Spring Dresses 2026 Casual Sleeveless Crewneck Aline Maxi...",
        image: "https://m.media-amazon.com/images/I/616v2WHxAWL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F2YT2727?tag=values0d4-20",
        price: "$46.98",
        rating: 4.3,
        reviewCount: 377,
      },
    ],
  },
];

// ─── BY BODY TYPE ──────────────────────────────────────────
export const bodyTypeSections: HomepageSection[] = [
  {
    id: "plus-size-dresses",
    title: "Plus Size Wedding Guest Dresses",
    description: "Gorgeous dresses designed to flatter curves beautifully. Available in extended sizes with comfortable, confidence-boosting fits.",
    slug: "plus-size-wedding-guest-dresses",
    products: [
      {
        title: "EYWOL Womens Plus Size Floral Tiered Ruffle Long Sleeve Evening Party Wedding...",
        image: "https://m.media-amazon.com/images/I/713-yL8UnhL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DXL5TYQV?tag=values0d4-20",
        price: "$66.99",
        rating: 4.5,
        reviewCount: 314,
      },
      {
        title: "Women's Plus Size Formal Party Cocktail Dress, Wedding Guest Evening Gown wit...",
        image: "https://m.media-amazon.com/images/I/71MkXE9OeJL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F4JS3XBL?tag=values0d4-20",
        price: "$79.99",
        rating: 4.4,
        reviewCount: 54,
      },
      {
        title: "SCOMCHIC Women Plus Size Midi Dresses Wedding Guest Short Sleeve V Neck Tie W...",
        image: "https://m.media-amazon.com/images/I/61UFYywOsEL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DMFV9CQC?tag=values0d4-20",
        price: "$39.99",
        rating: 4.1,
        reviewCount: 359,
      },
      {
        title: "SCOMCHIC Womens Plus Size Wedding Guest Cocktail Dresses Sweetheart Neckline ...",
        image: "https://m.media-amazon.com/images/I/61kV0ko2UoL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DTHPYRBQ?tag=values0d4-20",
        price: "$39.99",
        rating: 4.3,
        reviewCount: 245,
      },
      {
        title: "VOUIAO Women's Daily Plus Size Dresses A Line Chiffon Wedding Guest Bridesmai...",
        image: "https://m.media-amazon.com/images/I/71Uac+tVcFL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FMJW4ZTD?tag=values0d4-20",
        price: "$58.99",
        rating: 4.1,
        reviewCount: 144,
      },
      {
        title: "Floerns Women's Plus Size Asymmetrical Neck Long Dress Ruched Slit Hem Cockta...",
        image: "https://m.media-amazon.com/images/I/51-zo-uOkfL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DSBCSV8H?tag=values0d4-20",
        price: "$39.99",
        rating: 4.4,
        reviewCount: 488,
      },
      {
        title: "Talisea Plus Size Formal Dresses - Wedding Guest Bridesmaid Evening Prom Chif...",
        image: "https://m.media-amazon.com/images/I/61OozCDMGFL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F83ZX89Y?tag=values0d4-20",
        price: "$65.99",
        rating: 4.3,
        reviewCount: 133,
      },
      {
        title: "SCOMCHIC Womens Plus Size Wedding Guest Dress Formal Lace Wrap V Neck High Lo...",
        image: "https://m.media-amazon.com/images/I/71pMjLF3DnL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DFQ89QYS?tag=values0d4-20",
        price: "$47.98",
        rating: 4.2,
        reviewCount: 498,
      },
    ],
  },
  {
    id: "petite-dresses",
    title: "Petite Wedding Guest Dresses",
    description: "Perfectly proportioned dresses for petite frames. These styles are designed to flatter shorter heights without overwhelming your figure.",
    slug: "petite-wedding-guest-dresses",
    products: [
      {
        title: "KUTUMAI Off The Shoulder Maxi Long Dress Corset Ruched Bodycon Cocktail Forma...",
        image: "https://m.media-amazon.com/images/I/611kJ8-TG5L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0D8BDLPMP?tag=values0d4-20",
        price: "$63.99",
        rating: 4.4,
        reviewCount: 1015,
      },
      {
        title: "Memoriesea Women's Sexy One Shoulder High Split Cocktail Wedding Party Maxi D...",
        image: "https://m.media-amazon.com/images/I/61ikOR7JYaL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CN64VSG3?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 5749,
      },
      {
        title: "EYNMIN Women's Sleeveless Bodycon Corset Maxi Dress Spaghetti Strap Ruched El...",
        image: "https://m.media-amazon.com/images/I/51RsPaE0yYL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CN8W7THP?tag=values0d4-20",
        price: "$68.99",
        rating: 4.3,
        reviewCount: 2227,
      },
      {
        title: "BTFBM Women Summer Floral Maxi Dresses Elegant Spaghetti Strap Dress Printed ...",
        image: "https://m.media-amazon.com/images/I/71JMz6nMvFL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DP71TDT7?tag=values0d4-20",
        price: "$46.99",
        rating: 4.5,
        reviewCount: 1526,
      },
      {
        title: "CUPSHE Women's Mini Dresses Casual Spring V Neck Chiffon Long Peasant Sleeves...",
        image: "https://m.media-amazon.com/images/I/71CwKwMLckL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BCKLNGPK?tag=values0d4-20",
        price: "$45.99",
        rating: 4.1,
        reviewCount: 4619,
      },
      {
        title: "Alex Evenings Women's Tea Length Dress with Rosette Detail",
        image: "https://m.media-amazon.com/images/I/713Q0EM78ZL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B082TZ7QNQ?tag=values0d4-20",
        price: "$112.37",
        rating: 4.1,
        reviewCount: 393,
      },
      {
        title: "ZESICA Women's 2026 Summer Halter Cocktail Dresses Sleeveless Ruffle Tiered C...",
        image: "https://m.media-amazon.com/images/I/71IozgzMreL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CPLT19PD?tag=values0d4-20",
        price: "$56.99",
        rating: 4.4,
        reviewCount: 1170,
      },
      {
        title: "DRESSTELLS Women's Cocktail Dresses, Formal Wedding Guest Modest Church Vinta...",
        image: "https://m.media-amazon.com/images/I/61GoY+62WXL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B07RDCY9XW?tag=values0d4-20",
        price: "$39.99",
        rating: 4.2,
        reviewCount: 22078,
      },
    ],
  },
  {
    id: "maternity-dresses",
    title: "Maternity Wedding Guest Dresses",
    description: "Beautiful and comfortable dresses designed with growing bumps in mind. Look stunning while staying comfortable all day.",
    slug: "maternity-wedding-guest-dresses",
    products: [
      {
        title: "GRACE KARIN Summer Floral Dress for Women 2026,Off The Shoulder Smocked Bride...",
        image: "https://m.media-amazon.com/images/I/71vzvNZiVLL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CPJGYK97?tag=values0d4-20",
        price: "$49.99",
        rating: 4.1,
        reviewCount: 1046,
      },
      {
        title: "Maternity Dress Baby Shower - 2025 Photoshoot Pregnancy Summer Floral Maxi Of...",
        image: "https://m.media-amazon.com/images/I/818JLw41TQL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FBRTQ68W?tag=values0d4-20",
        price: "$47.99",
        rating: 4.5,
        reviewCount: 118,
      },
      {
        title: "REORIA Long Sleeve Wedding Guest Maxi Dresses for Women Sheer Mesh Square Nec...",
        image: "https://m.media-amazon.com/images/I/610QlJ04yoL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH6PH41V?tag=values0d4-20",
        price: "$49.97",
        rating: 4.5,
        reviewCount: 500,
      },
      {
        title: "OUGES Maternity Maxi Dress Wrap Baby Shower Pregnancy Dresses for Photoshoot ...",
        image: "https://m.media-amazon.com/images/I/71zHYjvpgwL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BW971MZC?tag=values0d4-20",
        price: "$32.99",
        rating: 4.5,
        reviewCount: 1841,
      },
      {
        title: "OUGES Womens 2026 Summer Maternity Photoshoot Dress Boho Maxi Smocked Baby Sh...",
        image: "https://m.media-amazon.com/images/I/71Gq65aWJEL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F1FC763L?tag=values0d4-20",
        price: "$50.99",
        rating: 4.4,
        reviewCount: 457,
      },
      {
        title: "KUTUMAI Women Off Shoulder Bodycon Maxi Dress Long Sleeve Mesh Ruched Party F...",
        image: "https://m.media-amazon.com/images/I/711y17DOYOL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DNZFD67T?tag=values0d4-20",
        price: "$63.99",
        rating: 4.1,
        reviewCount: 717,
      },
      {
        title: "MEROKEETY Women's 2026 Summer Sleeveless Midi Dress One Shoulder Knot Smocked...",
        image: "https://m.media-amazon.com/images/I/71pz+vP+3rL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BL6WSCZC?tag=values0d4-20",
        price: "$42.99",
        rating: 4.2,
        reviewCount: 2298,
      },
      {
        title: "Milumia Women's Maternity Floral Mesh Split Strapless Tube Dress Bodycon Maxi...",
        image: "https://m.media-amazon.com/images/I/61wYuPiQr7L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0D5Y3M13F?tag=values0d4-20",
        price: "$48.99",
        rating: 4.4,
        reviewCount: 148,
      },
    ],
  },
];

// ─── BY STYLE ────────────────────────────────────────────
export const styleSections: HomepageSection[] = [
  {
    id: "long-dresses",
    title: "Long Wedding Guest Dresses",
    description: "Elegant floor-length and maxi dresses that make a dramatic entrance. Perfect for formal and black-tie weddings.",
    slug: "long-wedding-guest-dresses",
    products: [
      {
        title: "YMDUCH Women's Elegant Sleeveless Off Shoulder Bodycon Long Formal Party Even...",
        image: "https://m.media-amazon.com/images/I/511YfTNHu2L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B09VRN1NXL?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 8681,
      },
      {
        title: "PRETTYGARDEN Women's Summer One Shoulder Long Formal Dresses Sleeveless Ruche...",
        image: "https://m.media-amazon.com/images/I/61CkyHi94sL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B09YTWFM64?tag=values0d4-20",
        price: "$66.99",
        rating: 4.2,
        reviewCount: 3193,
      },
      {
        title: "VOUIAO Women's 2026 Spring Formal Evening Gown Elegant Long Prom Dress Weddin...",
        image: "https://m.media-amazon.com/images/I/61f51ieSILL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FJLTWFTJ?tag=values0d4-20",
        price: "$49.99",
        rating: 4.1,
        reviewCount: 183,
      },
      {
        title: "REORIA Women's Spring Mesh Sheer Long Sleeve Wedding Guest Dress Sexy Floral ...",
        image: "https://m.media-amazon.com/images/I/518UZUUjHlL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FF9YJDD5?tag=values0d4-20",
        price: "$49.97",
        rating: 4.4,
        reviewCount: 440,
      },
      {
        title: "Verdusa Women's Formal Wedding Guest Dress Halter Flowy Chiffon Asymmetrical ...",
        image: "https://m.media-amazon.com/images/I/51RVhLZ0X0L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CP3XT3R5?tag=values0d4-20",
        price: "$45.99",
        rating: 4.2,
        reviewCount: 769,
      },
      {
        title: "REORIA Women's Summer Cowl Neck Mesh Sleeveless Tank Dress Sexy Double Lined ...",
        image: "https://m.media-amazon.com/images/I/51TlDBbXqGL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DXKTHQ54?tag=values0d4-20",
        price: "$49.97",
        rating: 4.4,
        reviewCount: 210,
      },
      {
        title: "ZESICA Women's Long Sleeve Floral Bodycon Dress 2026 Spring Fall Ruched Mesh ...",
        image: "https://m.media-amazon.com/images/I/617sy+YX12L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH57DGCK?tag=values0d4-20",
        price: "$52.99",
        rating: 4.5,
        reviewCount: 649,
      },
      {
        title: "2026 Satin One Shoulder Maxi Dress for Women Summer Silk Formal Elegant Backl...",
        image: "https://m.media-amazon.com/images/I/614UGKM9uhL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DP2F28RL?tag=values0d4-20",
        price: "$49.99",
        rating: 4,
        reviewCount: 162,
      },
    ],
  },
  {
    id: "midi-dresses",
    title: "Midi Wedding Guest Dresses",
    description: "The most versatile wedding guest length. Midi dresses hit below the knee and work perfectly for any dress code.",
    slug: "midi-wedding-guest-dresses",
    products: [
      {
        title: "ZESICA Women's Summer Strapless Floral Midi Dress 2026 Bodycon Mesh Tube Wedd...",
        image: "https://m.media-amazon.com/images/I/71UczIhC4bL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FXWCV32B?tag=values0d4-20",
        price: "$58.99",
        rating: 4.6,
        reviewCount: 102,
      },
      {
        title: "ZESICA Women's Summer Sleeveless Halter Midi Dress 2026 Off Shoulder High Wai...",
        image: "https://m.media-amazon.com/images/I/51oz3E7J01L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DSVLWX75?tag=values0d4-20",
        price: "$50.99",
        rating: 4.1,
        reviewCount: 615,
      },
      {
        title: "ZESICA Women's Summer Short Sleeve Bodycon Midi Dress 2026 Spring Elegant For...",
        image: "https://m.media-amazon.com/images/I/61XLqcqjtqL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FXQKH878?tag=values0d4-20",
        price: "$55.99",
        rating: 4.5,
        reviewCount: 74,
      },
      {
        title: "PRETTYGARDEN Women's Summer Tulle Midi Dress Sleeveless Smocked Ruffle Flowy ...",
        image: "https://m.media-amazon.com/images/I/81jExGIhUDL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DZ6B2CFB?tag=values0d4-20",
        price: "$59.99",
        rating: 4.3,
        reviewCount: 1813,
      },
      {
        title: "DRESSTELLS Women's Cocktail Dresses, Formal Wedding Guest Graduation Party Hi...",
        image: "https://m.media-amazon.com/images/I/61Wy4amLjML._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DZ6Q3QYW?tag=values0d4-20",
        price: "$42.99",
        rating: 4.2,
        reviewCount: 891,
      },
      {
        title: "DRESSTELLS Women's Cocktail Dresses, Formal Wedding Guest Modest Church Vinta...",
        image: "https://m.media-amazon.com/images/I/61WMwbw68LL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B07RKLTM6C?tag=values0d4-20",
        price: "$36.99",
        rating: 4.2,
        reviewCount: 22078,
      },
      {
        title: "ZESICA Women's 2026 Spring Long Sleeve Bodycon Dress Mock Neck Wedding Guest ...",
        image: "https://m.media-amazon.com/images/I/51d1P544JiL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FCC1GGZZ?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 885,
      },
      {
        title: "CurvySweet Women's Formal Evening Midi Cocktail Dress Built-in Bra Ruched Sle...",
        image: "https://m.media-amazon.com/images/I/61b4g2caBrL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F3CG3CV9?tag=values0d4-20",
        price: "$54.99",
        rating: 4.4,
        reviewCount: 130,
      },
    ],
  },
  {
    id: "maxi-dresses",
    title: "Maxi Wedding Guest Dresses",
    description: "Flowing maxi dresses that are effortlessly elegant. These ankle-length styles are comfortable and chic for any season.",
    slug: "maxi-wedding-guest-dresses",
    products: [
      {
        title: "Verdusa Women's Floral Mesh Maxi Dresses Elegant Formal Long Sleeve Spring We...",
        image: "https://m.media-amazon.com/images/I/61NXa9j1ztL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F297J7G3?tag=values0d4-20",
        price: "$52.99",
        rating: 4.2,
        reviewCount: 330,
      },
      {
        title: "PRETTYGARDEN Women's Summer One Shoulder Long Formal Dresses Sleeveless Ruche...",
        image: "https://m.media-amazon.com/images/I/61CkyHi94sL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B09YTVKBQ1?tag=values0d4-20",
        price: "$66.99",
        rating: 4.2,
        reviewCount: 3193,
      },
      {
        title: "PRETTYGARDEN Women's 2026 Summer Wedding Guest Dress Sleeveless Ruffle Formal...",
        image: "https://m.media-amazon.com/images/I/61XyPkGW2YL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CNSJB7VT?tag=values0d4-20",
        price: "$59.99",
        rating: 4.3,
        reviewCount: 1462,
      },
      {
        title: "KUTUMAI Off The Shoulder Maxi Long Dress Corset Ruched Bodycon Cocktail Forma...",
        image: "https://m.media-amazon.com/images/I/61sVDF5i6XL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DYXVXLKD?tag=values0d4-20",
        price: "$64.99",
        rating: 4.4,
        reviewCount: 1015,
      },
      {
        title: "MEROKEETY Women's Spring Wedding Guest Dress 2026 Long Sleeve Bodycon Floral ...",
        image: "https://m.media-amazon.com/images/I/61MnvapCR4L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0D818MJL7?tag=values0d4-20",
        price: "$46.99",
        rating: 4.6,
        reviewCount: 1013,
      },
      {
        title: "MEROKEETY Women's Cocktail Dresses Summer 2026 Satin Strapless Tube Bodycon B...",
        image: "https://m.media-amazon.com/images/I/61x+lw2lFuL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C5MRZDTZ?tag=values0d4-20",
        price: "$48.99",
        rating: 4.1,
        reviewCount: 1069,
      },
      {
        title: "VOUIAO Women's 2026 Spring Formal Evening Gown Elegant Long Prom Dress Weddin...",
        image: "https://m.media-amazon.com/images/I/71D+vYjdN-L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FJLX2WBD?tag=values0d4-20",
        price: "$49.99",
        rating: 4.1,
        reviewCount: 183,
      },
      {
        title: "Memoriesea Women's Elegant Off Shoulder High Split Bodycon Evening Wedding Ma...",
        image: "https://m.media-amazon.com/images/I/515quu+toIL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FHWDPPD2?tag=values0d4-20",
        price: "$51.99",
        rating: 4.2,
        reviewCount: 457,
      },
    ],
  },
  {
    id: "floral-dresses",
    title: "Floral Wedding Guest Dresses",
    description: "Beautiful floral print dresses perfect for garden and outdoor weddings. Fresh, feminine, and always in style.",
    slug: "floral-wedding-guest-dresses",
    products: [
      {
        title: "GothDark Women's Summer Floral Mesh Ruffle Dress Short Sleeve Round Neck Wais...",
        image: "https://m.media-amazon.com/images/I/71HkhVu9R1L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DZT57FVK?tag=values0d4-20",
        price: "$38.99",
        rating: 4.3,
        reviewCount: 243,
      },
      {
        title: "Prinbara Womens One Shoulder Floral Bodycon Maxi Dress 2026 Summer High Split...",
        image: "https://m.media-amazon.com/images/I/81EroINqNzL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F2FZGJJG?tag=values0d4-20",
        price: "$29.98",
        rating: 4.5,
        reviewCount: 131,
      },
      {
        title: "PRETTYGARDEN Women's 2026 Spring Floral Spaghetti Strap Maxi Dress Stretch Se...",
        image: "https://m.media-amazon.com/images/I/61M7t3v6iUL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CNP4N39J?tag=values0d4-20",
        price: "$39.98",
        rating: 4.5,
        reviewCount: 1340,
      },
      {
        title: "Newshows Women's 2026 Lightweight Summer Wedding Guest Beach Vacation Casual ...",
        image: "https://m.media-amazon.com/images/I/71M5VqCawUS._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B095RGJBCH?tag=values0d4-20",
        price: "$34.39",
        rating: 4.3,
        reviewCount: 8871,
      },
      {
        title: "KUTUMAI Off The Shoulder Maxi Long Dress Corset Ruched Bodycon Cocktail Forma...",
        image: "https://m.media-amazon.com/images/I/61sVDF5i6XL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DYXVXLKD?tag=values0d4-20",
        price: "$64.99",
        rating: 4.4,
        reviewCount: 1015,
      },
      {
        title: "BTFBM Women Summer Floral Maxi Dresses Elegant Spaghetti Strap Dress Printed ...",
        image: "https://m.media-amazon.com/images/I/71gem062CHL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DP6ZZY1D?tag=values0d4-20",
        price: "$46.99",
        rating: 4.5,
        reviewCount: 1526,
      },
      {
        title: "BTFBM Dresses for Women Summer 2026 Formal Sleeveless Smocked Floral Long Wed...",
        image: "https://m.media-amazon.com/images/I/71tYzvJKx7L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FY6LW1Z8?tag=values0d4-20",
        price: "$45.99",
        rating: 4.6,
        reviewCount: 60,
      },
      {
        title: "GRACE KARIN Summer Floral Dress for Women 2026,Off The Shoulder Smocked Bride...",
        image: "https://m.media-amazon.com/images/I/71vzvNZiVLL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CPJGYK97?tag=values0d4-20",
        price: "$49.99",
        rating: 4.1,
        reviewCount: 1046,
      },
    ],
  },
  {
    id: "modest-dresses",
    title: "Modest Wedding Guest Dresses",
    description: "Elegant dresses with longer hemlines and higher necklines. Modest styles that are beautiful, fashionable, and appropriate.",
    slug: "modest-wedding-guest-dresses",
    products: [
      {
        title: "DRESSTELLS Women's Cocktail Dresses, Formal Wedding Guest Modest Church Vinta...",
        image: "https://m.media-amazon.com/images/I/61WMwbw68LL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B07RDCYKTM?tag=values0d4-20",
        price: "$35.99",
        rating: 4.2,
        reviewCount: 22078,
      },
      {
        title: "ZESICA Women's Long Sleeve Floral Bodycon Dress 2026 Spring Fall Ruched Mesh ...",
        image: "https://m.media-amazon.com/images/I/617sy+YX12L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH57DGCK?tag=values0d4-20",
        price: "$52.99",
        rating: 4.5,
        reviewCount: 649,
      },
      {
        title: "Long Black Formal Dresses for Women Gowns Evening Party Cocktail Dress,Split ...",
        image: "https://m.media-amazon.com/images/I/61wbcy3qmkL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0C53FB542?tag=values0d4-20",
        price: "$59.78",
        rating: 4.5,
        reviewCount: 2823,
      },
      {
        title: "PRETTYGARDEN Women's Smocked Midi Tulle Dress 2026 Summer Puffy Short Sleeve ...",
        image: "https://m.media-amazon.com/images/I/71jPEYNBw8L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DJNX5N7V?tag=values0d4-20",
        price: "$59.99",
        rating: 4.4,
        reviewCount: 1148,
      },
      {
        title: "Simplee Women's Floral Boho Long Sleeve Maxi Dress V Neck Empire Waist Swing ...",
        image: "https://m.media-amazon.com/images/I/81rkl6vd4VL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F7LV6CLP?tag=values0d4-20",
        price: "$49.99",
        rating: 4.6,
        reviewCount: 370,
      },
      {
        title: "REORIA Women's Spring Mesh Sheer Long Sleeve Wedding Guest Dress Sexy Floral ...",
        image: "https://m.media-amazon.com/images/I/51pFuZg91uL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FF9TT97W?tag=values0d4-20",
        price: "$49.97",
        rating: 4.4,
        reviewCount: 440,
      },
      {
        title: "Simplee Womens Floral Maxi Dress Short Sleeve Summer Boho Wedding Guest Dress...",
        image: "https://m.media-amazon.com/images/I/717oxUrfN8L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DPG2RXPR?tag=values0d4-20",
        price: "$49.99",
        rating: 4.3,
        reviewCount: 579,
      },
      {
        title: "ANRABESS Womens Floral Long Sleeve Maxi Dress V Neck Chiffon Flowy Boho A-Lin...",
        image: "https://m.media-amazon.com/images/I/71F4g7aab0L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FKFMWC4N?tag=values0d4-20",
        price: "$43.99",
        rating: 4,
        reviewCount: 117,
      },
    ],
  },
  {
    id: "long-sleeve-dresses",
    title: "Long Sleeve Wedding Guest Dresses",
    description: "Stylish long sleeve dresses for cooler weather weddings. These elegant options keep you warm while looking amazing.",
    slug: "long-sleeve-wedding-guest-dresses",
    products: [
      {
        title: "ZESICA Women's Long Sleeve Floral Bodycon Dress 2026 Spring Fall Ruched Mesh ...",
        image: "https://m.media-amazon.com/images/I/617sy+YX12L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH5BTXXW?tag=values0d4-20",
        price: "$52.99",
        rating: 4.5,
        reviewCount: 649,
      },
      {
        title: "REORIA Long Sleeve Wedding Guest Maxi Dresses for Women Sheer Mesh Square Nec...",
        image: "https://m.media-amazon.com/images/I/610QlJ04yoL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FH6PH41V?tag=values0d4-20",
        price: "$49.97",
        rating: 4.5,
        reviewCount: 500,
      },
      {
        title: "REORIA Women's Spring Mesh Sheer Long Sleeve Wedding Guest Dress Sexy Floral ...",
        image: "https://m.media-amazon.com/images/I/518UZUUjHlL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FF9YJDD5?tag=values0d4-20",
        price: "$49.97",
        rating: 4.4,
        reviewCount: 440,
      },
      {
        title: "ZESICA Women's 2026 Spring Long Sleeve Bodycon Dress Mock Neck Wedding Guest ...",
        image: "https://m.media-amazon.com/images/I/51d1P544JiL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FCC1GGZZ?tag=values0d4-20",
        price: "$54.99",
        rating: 4.3,
        reviewCount: 885,
      },
      {
        title: "Verdusa Women's Floral Mesh Maxi Dresses Elegant Formal Long Sleeve Spring We...",
        image: "https://m.media-amazon.com/images/I/61NXa9j1ztL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F298TMRF?tag=values0d4-20",
        price: "$52.99",
        rating: 4.2,
        reviewCount: 330,
      },
      {
        title: "BORIFLORS Women's Bodycon Ruched Mesh Long Sleeve Maxi Dress Mermaid Ruffle F...",
        image: "https://m.media-amazon.com/images/I/610oYJOTq5L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FX2MZQQW?tag=values0d4-20",
        price: "$35.99",
        rating: 4.4,
        reviewCount: 170,
      },
      {
        title: "ANRABESS Womens Floral Long Sleeve Maxi Dress V Neck Chiffon Flowy Boho A-Lin...",
        image: "https://m.media-amazon.com/images/I/71F4g7aab0L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FKFMWC4N?tag=values0d4-20",
        price: "$43.99",
        rating: 4,
        reviewCount: 117,
      },
      {
        title: "ZESICA Women's Spring Floral Off Shoulder Bodycon Maxi Dresses 2026 Long Slee...",
        image: "https://m.media-amazon.com/images/I/61Idn8rOrRL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FG82KC42?tag=values0d4-20",
        price: "$49.99",
        rating: 4.4,
        reviewCount: 190,
      },
    ],
  },
];

// ─── BY VENUE ────────────────────────────────────────────
export const venueSections: HomepageSection[] = [
  {
    id: "beach-dresses",
    title: "Beach Wedding Guest Dresses",
    description: "Light, flowy dresses perfect for seaside ceremonies. These breezy styles look stunning against the ocean backdrop.",
    slug: "beach-wedding-guest-dresses",
    products: [
      {
        title: "Women Sexy V Neck Sleeveless Mesh Ruffle Hem Bodycon Maxi Casual Backless Hig...",
        image: "https://m.media-amazon.com/images/I/51Rvv3xV60L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DCVPKW7H?tag=values0d4-20",
        price: "$40.49",
        rating: 4.2,
        reviewCount: 1107,
      },
      {
        title: "BTFBM Women Summer Floral Maxi Dresses Elegant Spaghetti Strap Dress Printed ...",
        image: "https://m.media-amazon.com/images/I/71gem062CHL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DP6Z37LT?tag=values0d4-20",
        price: "$46.99",
        rating: 4.5,
        reviewCount: 1526,
      },
      {
        title: "Newshows Women's 2026 Lightweight Summer Wedding Guest Beach Vacation Casual ...",
        image: "https://m.media-amazon.com/images/I/61DQcEDqr3L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B08M96SPYP?tag=values0d4-20",
        price: "$37.39",
        rating: 4.3,
        reviewCount: 8871,
      },
      {
        title: "ZESICA Women's 2026 Summer Halter Cocktail Dresses Sleeveless Ruffle Tiered C...",
        image: "https://m.media-amazon.com/images/I/71IozgzMreL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CPLT19PD?tag=values0d4-20",
        price: "$56.99",
        rating: 4.4,
        reviewCount: 1170,
      },
      {
        title: "KILIG Women's Summer Floral Beach Flowy Split Maxi Long Dresses",
        image: "https://m.media-amazon.com/images/I/71KMVmQfp6L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B09W9LDW8H?tag=values0d4-20",
        price: "$33.99",
        rating: 4.3,
        reviewCount: 6507,
      },
      {
        title: "ZESICA Women's 2026 Summer Sleeveless Halter Neck Ruffle Tiered Layed Chiffon...",
        image: "https://m.media-amazon.com/images/I/61b8ePYiToL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BS3J2RK2?tag=values0d4-20",
        price: "$59.99",
        rating: 4.4,
        reviewCount: 3196,
      },
      {
        title: "PRETTYGARDEN Women's Summer Floral One Shoulder Maxi Dress Knot Ruffle Boho B...",
        image: "https://m.media-amazon.com/images/I/71ZTGUNM7aL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BVLMY86Q?tag=values0d4-20",
        price: "$42.99",
        rating: 4.2,
        reviewCount: 7442,
      },
      {
        title: "MEROKEETY Womens Spring Wedding Guest Dress 2026 Summer Beach Floral Cocktail...",
        image: "https://m.media-amazon.com/images/I/61W03mAtRuL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0FX2MQH38?tag=values0d4-20",
        price: "$57.99",
        rating: 4.7,
        reviewCount: 54,
      },
    ],
  },
  {
    id: "garden-party-dresses",
    title: "Garden Party Wedding Guest Dresses",
    description: "Romantic and feminine dresses for outdoor garden weddings. Florals, pastels, and flowing silhouettes that complement natural settings.",
    slug: "garden-party-wedding-guest-dresses",
    products: [
      {
        title: "Sponsored Ad - PRETTYGARDEN Women's Summer Tulle Midi Dress Sleeveless Smocke...",
        image: "https://m.media-amazon.com/images/I/81oyhrntPZL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DZ6FY5H2?tag=values0d4-20",
        price: "$59.99",
        rating: 4.3,
        reviewCount: 1813,
      },
      {
        title: "Sponsored Ad - ZESICA Women's 2026 Summer Floral Sleeveless Maxi Dress Ruffle...",
        image: "https://m.media-amazon.com/images/I/61dGOo3ptWL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DSBVJCDW?tag=values0d4-20",
        price: "$52.99",
        rating: 4.2,
        reviewCount: 248,
      },
      {
        title: "GRACE KARIN Womens Summer One Shoulder Sleeveless Dresses Floral Flowy Ruffle...",
        image: "https://m.media-amazon.com/images/I/710VBUzpu3L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0D4ZDK3MF?tag=values0d4-20",
        price: "$58.99",
        rating: 4.3,
        reviewCount: 359,
      },
      {
        title: "Maxigerui Women's Summer Floral Maxi Dress Spring Wedding Guest Dress 2026",
        image: "https://m.media-amazon.com/images/I/71S9IZ4dP2L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CZP7K8XT?tag=values0d4-20",
        price: "$53.99",
        rating: 4.3,
        reviewCount: 697,
      },
      {
        title: "BTFBM Women Summer Floral Maxi Dresses Elegant Spaghetti Strap Dress Printed ...",
        image: "https://m.media-amazon.com/images/I/71gem062CHL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DP6ZZY1D?tag=values0d4-20",
        price: "$46.99",
        rating: 4.5,
        reviewCount: 1526,
      },
      {
        title: "ZESICA Women's Summer Strapless Bodycon Maxi Dress 2026 Ribbed Knit Backless ...",
        image: "https://m.media-amazon.com/images/I/51k0gv0-7rL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DZD3YLMH?tag=values0d4-20",
        price: "$53.99",
        rating: 4.2,
        reviewCount: 401,
      },
      {
        title: "DRESSTELLS Women Formal Wedding Guest Long Cocktail Party One Shoulder Mesh R...",
        image: "https://m.media-amazon.com/images/I/61JR2C7i4rL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DS252K1M?tag=values0d4-20",
        price: "$36.99",
        rating: 4.6,
        reviewCount: 180,
      },
      {
        title: "Belle Poque Sun Dresses for Women Spring Summer Floral Midi Flowy Spaghetti R...",
        image: "https://m.media-amazon.com/images/I/71k3Zav+n6L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DQH67DSH?tag=values0d4-20",
        price: "$42.99",
        rating: 4.4,
        reviewCount: 724,
      },
    ],
  },
  {
    id: "indian-wedding-dresses",
    title: "Indian Wedding Guest Dresses",
    description: "Vibrant, colorful dresses and outfits perfect for Indian wedding celebrations. Think rich fabrics, bright colors, and elegant embellishments.",
    slug: "indian-wedding-guest-dresses",
    products: [
      {
        title: "Shopping Queen Women's Georgette Embroidery Straight Kurta and Sharara Set",
        image: "https://m.media-amazon.com/images/I/61EETQbWvgL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CBVH6HNG?tag=values0d4-20",
        price: "$69.99",
        rating: 4.2,
        reviewCount: 613,
      },
      {
        title: "Shopping Queen Women's Georgette Chikankari Embroidery Kurta set with Dupatta",
        image: "https://m.media-amazon.com/images/I/718uNRM8xXL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0CBVFL93P?tag=values0d4-20",
        price: "$63.99",
        rating: 4.3,
        reviewCount: 324,
      },
      {
        title: "TRENDMALLS Women's Vichitra Silk Anarkali Suit Set with Jacquard Dupatta for ...",
        image: "https://m.media-amazon.com/images/I/81qM9fgvHqL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0F7FP8BK9?tag=values0d4-20",
        price: "$99.00",
        rating: 4,
        reviewCount: 55,
      },
      {
        title: "STELLACOUTURE women's indian traditional full length heavy embroidered ethnic...",
        image: "https://m.media-amazon.com/images/I/81a+I9K5xJL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B08D8HCKZ9?tag=values0d4-20",
        price: "$84.99",
        rating: 4.1,
        reviewCount: 86,
      },
      {
        title: "Indian Style lehenga choli for women Wedding Party Wear Dress fully stitched",
        image: "https://m.media-amazon.com/images/I/71zl46liX+L._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0B3DGCK8X?tag=values0d4-20",
        price: "$79.99",
        rating: 4.5,
        reviewCount: 69,
      },
      {
        title: "Miusol Women's Elegant Sequin Lace Contrast Chiffon Split Style Evening Party...",
        image: "https://m.media-amazon.com/images/I/71qgqnEeFVL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0DNZ526BN?tag=values0d4-20",
        price: "$65.99",
        rating: 4.3,
        reviewCount: 100,
      },
      {
        title: "Shopping Queen Women's Georgette Embroidered Kurta and Sharara & Dupatta Set",
        image: "https://m.media-amazon.com/images/I/61m6Lv2MRSL._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B0BPR6YW5M?tag=values0d4-20",
        price: "$64.99",
        rating: 4.2,
        reviewCount: 116,
      },
      {
        title: "Nivah Fashion Women's Georgette Embroidery Anarkali Suit Set Stitched",
        image: "https://m.media-amazon.com/images/I/81LKaFXaddS._AC_UL500_.jpg",
        url: "https://www.amazon.com/dp/B093C271YC?tag=values0d4-20",
        price: "$80.00",
        rating: 4.1,
        reviewCount: 232,
      },
    ],
  },
];

// ─── HOMEPAGE FAQS ──────────────────────────────────────────
export const homepageFaqs: FAQ[] = [
  {
    question: "What should I wear as a wedding guest?",
    answer: "The best wedding guest dress depends on the dress code, venue, and season. For formal weddings, choose a floor-length or midi dress in an elegant fabric. For casual weddings, a pretty sundress or flowy midi works perfectly. Always check the invitation for dress code guidance and consider the venue — a beach wedding calls for lighter fabrics than a ballroom event.",
  },
  {
    question: "What colors should I avoid as a wedding guest?",
    answer: "The main color to avoid is white, cream, or ivory — anything that could be mistaken for a bridal gown. Some couples also prefer guests avoid wearing all-black to their wedding. Very bright neon colors or overly flashy outfits that might distract from the bride should also be reconsidered. When in doubt, opt for jewel tones, pastels, or rich earth tones.",
  },
  {
    question: "Is it OK to wear black to a wedding?",
    answer: "Yes, black is generally acceptable for most weddings, especially for evening or formal events. A chic black cocktail dress or elegant black gown is a classic and sophisticated choice. However, for very casual daytime or outdoor weddings, you might want to opt for something more colorful. If you're unsure, you can always add colorful accessories to brighten up a black dress.",
  },
  {
    question: "What is cocktail attire for a wedding?",
    answer: "Cocktail attire means a dress that falls at or just above the knee to mid-calf (midi length). It's dressier than casual but not as formal as black tie. Think elegant fabrics like silk, chiffon, or lace in solid colors or tasteful prints. Pair with heels or dressy flats and elegant jewelry. A well-fitted cocktail dress is one of the most versatile options for wedding guest attire.",
  },
  {
    question: "Can I wear a long dress to a casual wedding?",
    answer: "Absolutely! A flowy maxi dress in a casual fabric like cotton or jersey is perfect for casual weddings. The key is choosing relaxed silhouettes and fabrics that don't look overly formal. Pair it with flat sandals or wedges rather than formal heels to keep the look appropriately casual and comfortable.",
  },
  {
    question: "What should I wear to a beach wedding?",
    answer: "For a beach wedding, choose light, breathable fabrics like chiffon, cotton, or linen. Flowy midi or maxi dresses work beautifully. Avoid heavy fabrics and overly structured styles. Opt for flat sandals, wedges, or block heels that won't sink in the sand. Bright colors, tropical prints, and pastels all work wonderfully for seaside celebrations.",
  },
  {
    question: "How much should I spend on a wedding guest dress?",
    answer: "A great wedding guest dress doesn't have to break the bank. Amazon offers beautiful options ranging from $25 to $60 that look much more expensive than their price tag. The key is focusing on fit and fabric quality rather than brand names. Many of the most popular wedding guest dresses on Amazon are under $40 and have thousands of positive reviews.",
  },
  {
    question: "What should I wear to a fall wedding?",
    answer: "Fall weddings call for rich, warm colors like burgundy, emerald green, rust, navy, and plum. Long sleeves or three-quarter sleeves are perfect for cooler weather. Fabrics like velvet, satin, and chiffon add a seasonal elegance. Midi and maxi lengths work well, and you can layer with a stylish wrap or shawl for outdoor ceremonies.",
  },
];
